development:
  adapter: mysql2
  encoding: utf8
  database: idifyspree_production
  username: root
  password: ubuntu
  host: localhost
  pool: 5
  timeout: 5000
  
test:
  adapter: mysql2
  encoding: utf8
  database: idifyspree_test
  username: root
  password: ubuntu
  host: localhost
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: idifyspree_production
  username: root
  password: ubuntu
  host: localhost
  pool: 5
  timeout: 5000

